model:
  path: "models/pineaple_fruit_count/best.pt"

inference:
  imgsz: 640
  conf: 0.05

paths:
  input: "data/pineaple/counting_data/pineaple_count.mp4"
  output: "data/pineaple/counting_data/output/pineaple_count"
