model:
  name: "crop_segmentation_yolo11"
  data_yaml: "datasets/crop_segmentation/data.yaml"
  output_dir: "models/crop_segmentation_yolo11"

training:
  epochs: 250
  batch_size: 16
  imgsz: 640
  device: "auto"  # "auto", "cuda", or "cpu"

