model:
  name: "pineaple_fruit_count"
  data_yaml: "datasets/pineaple_fruit_count/data.yaml"
  output_dir: "models/pineaple_fruit_count"

training:
  epochs: 250
  batch_size: 16
  imgsz: 640
  device: "auto"  # "auto", "cuda", or "cpu"

