model:
  name: "jima_in_situ"
  data_yaml: "datasets/jima_in_situ/data.yaml"
  output_dir: "models/jima_in_situ"

training:
  epochs: 10 
  batch_size: 16
  imgsz: 640
  device: "auto"  # "auto", "cuda", or "cpu"

